service: smart-signal
provider:
  name: aws
  runtime: python3.8
  stage: prod
  profile: smart-signal-sls
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - execute-api:ManageConnections
      Resource: "*"

package:
  include:
    - src/**
  exclude:
    - README.md

plugins:
  - serverless-python-requirements
  - serverless-step-functions

custom:
  pythonRequirements:
    dockerizePip: true

resources:
  Outputs:
    TriggerPopulate:
      Value:
        Ref: TriggerPopulate
    # TriggerAlgorithms:
    #   Value:
    #     Ref: TriggerAlgorithms

functions:
  connectWebsocket:
    handler: src/api/websocket.connect
    events:
     - websocket:
        route: $connect
     - websocket:
        route: $disconnect
  getWebsocketPrices:
    handler: src/api/websocket.get_websocket_prices
    events:
     - websocket:
        route: getWebsocketPrices

  btc-populate:
    handler: src/populate/btc-populate.populate
    timeout: 15
    environment:
      statemachine_arn: ${self:resources.Outputs.TriggerPopulate.Value}

  getData:
    handler: src/api/get_data.get_data
    events:
      - http:
          path: get-data
          method: get
      - http:
          path: get-data
          method: options
          integration: lambda
          cors:
            origin: "*"

  indicators:
    handler: src/indicators/indicators.calculate
    events:
      - http:
          path: indicators
          method: get
          # request:
          #   parameters:
          #     querystrings:
          #       timeframe: true
          #       sell_val: true
          #       buy_val: true
          #       strength_adjust: true
      - http:
          path: indicators
          method: options
          integration: lambda
          cors:
            origin: "*"

  # algorithms:
  #   handler: src/algorithms/algorithms.calculate
  #   timeout: 60
  #   events:
  #    - schedule: rate(1 hour)
    # environment:
    #   statemachine_arn: ${self:resources.Outputs.TriggerAlgorithms.Value}

stepFunctions:
  stateMachines:
    triggerPopulateFunc:
      name: TriggerPopulate
      definition:
        Comment: "Invoke populate lambda every second"
        StartAt: ConfigureCount
        States:
          ConfigureCount:
            Type: Pass
            Result:
              index: 0
            ResultPath: "$.iterator"
            Next: Iterator
          Iterator:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:095630622700:function:smart-signal-prod-btc-populate
            ResultPath: "$.iterator"
            Next: IsCountReached
          IsCountReached:
            Type: Choice
            Choices:
            - Variable: "$.iterator.index"
              NumericLessThan: 6
              Next: Wait
            Default: Done
          Wait:
            Type: Wait
            Seconds: 9
            Next: Iterator
          Done:
            Type: Pass
            End: true

    # triggerAlgorithmsFunc:
    #   name: TriggerAlgorithms
    #   definition:
    #     Comment: "Invoke algorithm lambda every second"
    #     StartAt: ConfigureCount
    #     States:
    #       ConfigureCount:
    #         Type: Pass
    #         Result:
    #           index: 0
    #         ResultPath: "$.iterator"
    #         Next: Iterator
    #       Iterator:
    #         Type: Task
    #         Resource: arn:aws:lambda:us-east-1:095630622700:function:smart-signal-prod-algorithms
    #         ResultPath: "$.iterator"
    #         Next: IsCountReached
    #       IsCountReached:
    #         Type: Choice
    #         Choices:
    #         - Variable: "$.iterator.index"
    #           NumericLessThan: 60
    #           Next: Iterator
    #         Default: Done
    #       Done:
    #         Type: Pass
    #         End: true